[package]
name = "samira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0" }
serde = { version = "1.0" }
hyper-tls = "0.5.0"
hyper = { version = "0.14.23", features = ["client", "http1"]}
tokio-native-tls = "0.3.0"
tokio-tungstenite = { version = "0.18", features = ["native-tls"], optional = true }
futures-util = { version = "0.3.25", optional = true }
tokio = { version = "1.24.2", features = ["sync", "rt"], optional = true }

[features]
default = []
ws = ["dep:tokio-tungstenite", "dep:tokio", "dep:futures-util"]