[package]
name = "irelia"
version = "0.5.6"
edition = "2021"
description = "A Rust wrapper around the native LoL APIs"
license = "MIT"
repository = "https://github.com/AlsoSylv/Irelia"
homepage = "https://github.com/AlsoSylv/Irelia"
documentation = "https://docs.rs/irelia"
readme = "../README.md"
categories = ["riot", "league", "league of legends", "lcu", "riot-games"]

[dependencies]
# Required across all features
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
rustls = { version = "0.22", default-features = false }
rustls-pemfile = { version = "2.1", default-features = false }
irelia_encoder = { path = "../encoder", version = "0.1" }
# Optional across some features
http-body-util = { version = "0.1", optional = true }
sysinfo = { version = "0.30", optional = true, default-features = false }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
erased-serde = { version = "0.4", optional = true }
hashlink = { version = "0.9.0", optional = true, features = ["serde_impl"] }

[dependencies.hyper-rustls]
version = "0.26.0"
optional = true
default-features = false
features = ["http1", "rustls-native-certs", "ring"]

[dependencies.futures-util]
version = "0.3"
features = ["sink"]
optional = true
default-features = false

[dependencies.tokio]
version = "1.37"
default-features = false
optional = true

[dependencies.tokio-tungstenite]
version = "0.21"
features = ["__rustls-tls"]
optional = true

[dependencies.hyper]
version = "1.2"
features = ["http1"]
default-features = false
optional = true

[dependencies.hyper-util]
version = "0.1"
features = ["client-legacy", "http1"]
default-features = false
optional = true

[dev-dependencies]
rand = "0.8.5"
base64 = "0.22.0"

[dev-dependencies.tokio]
version = "1.37"
features = ["sync", "rt", "macros", "rt-multi-thread"]

[features]
default = [
    "full",
    ]
full = [
    "rest", 
    "in_game", 
    "ws",
    "tauri",
    "batched",
    ]

rest = [
    "dep:serde",
    "dep:serde_derive",
    "dep:hyper", 
    "dep:hyper-util",
    "dep:http-body-util",
    "dep:hyper-rustls",
    "dep:sysinfo",
    "dep:hashlink"
    ]

in_game = [
    "dep:serde", 
    "dep:hyper", 
    "dep:hyper-util",
    "dep:http-body-util",
    "dep:serde_derive",
    "dep:hyper-rustls",
    ]

ws = [
    "dep:tokio-tungstenite", 
    "dep:tokio", 
    "dep:futures-util",
    "dep:sysinfo",
    "tokio/sync",
    "tokio/rt"
    ]

batched = [
    "dep:erased-serde",
    "dep:futures-util",
    "rest",
    ]

tauri = [
    ]
encoder_nightly = ["irelia_encoder/nightly"]
encoder_simd = ["irelia_encoder/simd"]

[package.metadata.docs.rs]
features = ["full"]