[package]
name = "irelia"
version = "0.4.2"
edition = "2021"
description = "A Rust wrapper around the native LoL APIs"
license = "MIT"
repository = "https://github.com/AlsoSylv/Irelia"
homepage = "https://github.com/AlsoSylv/Irelia"
documentation = "https://docs.rs/irelia"
readme = "../README.md"

[dependencies]
# Required across all features
serde_json = { version = "1.0" }
rustls = "0.22"
rustls-pemfile = "2.0"
irelia_encoder = { path = "../encoder", version = "0.1" }
# Optional across some features
hyper-rustls = { version = "0.26.0", optional = true }
http-body-util = { version = "0.1.0", optional = true }
sysinfo = { version = "0.30", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
erased-serde = { version = "0.4", optional = true }

[dependencies.futures-util]
version = "0.3"
features = ["std", "sink"]
optional = true
default-features = false

[dependencies.tokio]
version = "1.24"
features = ["sync", "rt"]
optional = true

[dependencies.tokio-tungstenite]
version = "0.21"
features = ["__rustls-tls"]
optional = true

[dependencies.hyper]
version = "1.1"
features = ["client", "http1"]
optional = true

[dependencies.hyper-util]
version = "0.1"
features = ["client-legacy", "http1", "tokio"]
optional = true

[dev-dependencies]
rand = "0.8.5"
base64 = "0.21.0"

[dev-dependencies.tokio]
version = "1.27"
features = ["sync", "rt", "macros"]

[features]
default = [
    "full",
    ]
full = [
    "rest", 
    "in_game", 
    "ws",
    "tauri",
    "batched",
    ]

rest = [
    "dep:serde", 
    "dep:hyper", 
    "dep:hyper-util",
    "dep:http-body-util",
    "dep:futures-util",
    "dep:hyper-rustls",
    "dep:sysinfo",
    ]

in_game = [
    "dep:serde", 
    "dep:hyper", 
    "dep:hyper-util",
    "dep:http-body-util",
    "dep:serde_derive",
    "dep:hyper-rustls",
    ]

ws = [
    "dep:tokio-tungstenite", 
    "dep:tokio", 
    "dep:futures-util",
    "dep:sysinfo",
    ]

batched = [
    "dep:erased-serde",
    "rest",
    ]

tauri = [
    ]
encoder_nightly = ["irelia_encoder/nightly"]
encoder_simd = ["irelia_encoder/simd"]

[package.metadata.docs.rs]
all-features = true