[package]
name = "irelia"
version = "0.3.0"
edition = "2021"
description = "A Rust wrapper around the native LoL APIs"
license = "MIT"
repository = "https://github.com/AlsoSylv/Irelia"
homepage = "https://github.com/AlsoSylv/Irelia"
documentation = "https://docs.rs/irelia"
readme = "README.md"

[dependencies]
# Required across all features
serde_json = { version = "1.0" }
hyper-rustls = "0.24.0"
rustls = "0.21.0"
rustls-pemfile = "1.0.2"
sysinfo = "0.28.4"
# Optional across some features
# hyper-tls = { version = "0.5.0", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
erased-serde = { version = "0.3", optional = true }

[dependencies.futures-util]
version = "0.3"
features = ["std", "sink"]
optional = true
default-features = false

[dependencies.tokio]
version = "1.24"
features = ["sync", "rt"]
optional = true

[dependencies.tokio-tungstenite]
version = "0.19"
features = ["__rustls-tls"]
optional = true

[dependencies.hyper]
version = "0.14"
features = ["client", "http1"]
optional = true

[dev-dependencies]
rand = "0.8.5"
base64 = "0.21.0"

[dev-dependencies.tokio]
version = "1.24"
features = ["sync", "rt", "macros"]

[features]
default = [
    "rest"
    ]
full = [
    "rest", 
    "in_game", 
    "ws"
    ]

rest = [
    "dep:serde", 
    "dep:hyper", 
    "dep:futures-util",
    "dep:erased-serde"
    ]

in_game = [
    "dep:serde", 
    "dep:hyper", 
    "dep:serde_derive"
    ]

ws = [
    "dep:tokio-tungstenite", 
    "dep:tokio", 
    "dep:futures-util"
    ]

[package.metadata.docs.rs]
all-features = true