/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsLcuClient = LcuClient
export class LcuClient {
  /** `try` to establish a new connection to the LCU API, throwing an error otherwise */
  constructor()
  /**
   * `try` to establish a new connection to the LCU API, throwing an error otherwise
   * `force_lock_file` - whether the lock file should ALWAYS be read
   */
  static new(forceLockFile: boolean): JsLcuClient
  head(endpoint: string): Promise<Record<string, string>>
  delete(endpoint: string): Promise<any | null>
  /** Get an endpoint from the LCU */
  get(endpoint: string): Promise<any | null>
  patch(endpoint: string, body: any): Promise<any | null>
  patch(endpoint: string): Promise<any | null>
  post(endpoint: string, body: any): Promise<any | null>
  post(endpoint: string): Promise<any | null>
  put(endpoint: string, body: any): Promise<any | null>
  put(endpoint: string): Promise<any | null>
  url(): string
  authHeader(): string
}
